open prev/next labeled image
CVHub520/X-AnyLabeling pull request #452
Opened 2024-06-10 14:24 UTC by JiamingJiao

Press Q/E (Ctrl+Shift+Q/E) to go to previous/next labeled image. It is useful when you are reviewing a discontinuously labeled sequence of images.

2024-06-11 01:29 UTC, CVHub520 commented on anylabeling/configs/anylabeling_config.yaml
> +  open_next_labeled: [E, Ctrl+Shift+E]
hotkey conflict

2024-06-16 02:10 UTC, JiamingJiao commented
I changed the shortcuts to Z/C (Ctrl+Shift+Z/C) and added icons for the buttons.

2024-06-26 02:03 UTC, CVHub520 commented
Hi @JiamingJiao,

Thank you for your contribution to our project. We appreciate your effort and interest in improving our software.

I have reviewed your pull request, and there are a few changes we would like you to make to ensure it meets our project standards. Additionally, it seems there are some merge conflicts that need to be resolved.

Could you please address the feedback provided and resolve the merge conflicts? Once you’ve made the necessary changes, feel free to update the pull request, and we will be happy to review it again.

If you need any assistance or have any questions, please don’t hesitate to reach out. We are here to help.

Looking forward to your updated submission.

2024-06-26 02:07 UTC, CVHub520 commented
There are a couple of adjustments we need to make to ensure it aligns with our project requirements:
1. Please use the [Ctrl+Shift+D] and [Ctrl+Shift+A] keyboard shortcuts to trigger the desired functionality.
2. You may need to remove all relevant icons from the interface as part of this update.

2024-06-26 02:08 UTC, CVHub520 requested changes
There are a couple of adjustments we need to make to ensure it aligns with our project requirements:

Please use the [Ctrl+Shift+D] and [Ctrl+Shift+A] keyboard shortcuts to trigger the desired functionality.
You may need to remove all relevant icons from the interface as part of this update.

2024-06-29 13:21 UTC, CVHub520 commented
The current PR has been implemented in the latest [#8f5d0e6](https://github.com/CVHub520/X-AnyLabeling/commit/8f5d0e678272a2c478d52f9e9d1f545f72582503) branch and will be closed. Thank you again for your contribution!

2024-06-29 13:21 UTC, closed without merging