关于导出对齐, 标注检验, 保存子图 和 自动标注加速的修改
CVHub520/X-AnyLabeling pull request #762
Opened 2024-12-26 09:59 UTC by chevydream

## 一.与导出有关的修改

1) 导出yolo标签时, 对齐到小数点后6位
2) 涉及到的文件: label_converter.py

## 二.与检验有关的修改

1) 增加检测结果与原有标签的iou计算, 并找出: 0)标准, 1)多检, 2)漏检, 3)偏移
2) 转存多检, 漏检, 偏移三种标签和图片
3) 转存时, 将 多检 和 偏移 的框也画在原图片上, 方便人工矫正
4) 将 保留现有标签 改成了 提取疑错标签, 还不能用, 可能需要做本地化处理  
5) 涉及到的文件: label_widget.py, zh_CN.ts

## 三.与保存子图的修改

1. 保存子图时, 文件名中应该包含原图像的文件名, 方便后续的子图和原图的对应
2. 保存子图时, 不支持中文路径的问题
3. 涉及到的文件: image_dialog.py

## 四.推理加速的修改

1. 增加了一些耗时打印, 通过这些打印发现: 耗时主要在load_file()和to_rgb_cv_img()两个函数中  
2. 通过测试发现: 推理时, 发现根本不需要调用load_file函数, 只需执行其中的五句就行了
3. 通过测试发现: 推理时, 发现根本不需要调用progress_dialog.setValue()函数
4. 保存label时, 若没有图片数据, 则基于图片路径读取宽和高; 否则, 使用图片数据的宽高
5. 修改LabelFile类, 让其支持只加载标签数据, 不加载图片数据
6. 修改save_labels函数, 若没有图片数据, 则基于图片路径读取宽和高; 否则, 使用图片数据的宽高
7. 自动标注时, 不绘制目标框 和 侧边栏中的复选框, 以加快速度
8. 涉及到的文件: label_widget.py, yolo.py, canvas.py

2024-12-27 01:28 UTC, chevydream commented
上次提交中存在两处BUG, 修改了

2024-12-27 03:59 UTC, chevydream commented
又发现两处BUG, 并修改了

2024-12-28 03:22 UTC, CVHub520 commented
@chevydream 您好，请将主分支最新的代码合并到您的PR中，完成后我会进行合并。

2024-12-29 01:06 UTC, CVHub520 commented
您好，麻烦按照此[分支](https://github.com/CVHub520/X-AnyLabeling/tree/chevydream-main)进行提交尽快合并，不要做过多的个性化修改。

2024-12-30 02:22 UTC, chevydream commented
收到,今天合并

2024-12-30 05:51 UTC, CVHub520 commented
> 收到,今天合并

感谢整理，这边重新提了些修改意见，可以先处理下。如果您在修改过程中遇到任何问题，欢迎随时提出，我们再做讨论。

2024-12-30 10:01 UTC, CVHub520 requested changes
请根据要求做出相应修改。

2024-12-30 10:42 UTC, chevydream commented on README.md
已改

2024-12-30 10:42 UTC, chevydream commented on anylabeling/app.py
已改

2024-12-30 10:42 UTC, chevydream commented on anylabeling/views/labeling/label_converter.py
已改

2024-12-30 10:44 UTC, chevydream commented on anylabeling/views/labeling/label_widget.py
> +            self.label_file = LabelFile(osp.splitext(filename)[0] + ".json", osp.dirname(filename), False)
已改

2024-12-30 12:38 UTC, chevydream commented on anylabeling/views/labeling/label_widget.py
> +        print(f"{self.filename} 耗时: {infer_time * 1000:.2f}ms")
已改

2024-12-30 12:40 UTC, chevydream commented on anylabeling/services/auto_labeling/__base__/yolo.py
> +import time
已改

2024-12-30 12:57 UTC, chevydream commented on anylabeling/views/labeling/label_widget.py
> +    def set_dirty(self, flag=0):
已去除

2024-12-30 12:57 UTC, chevydream commented on anylabeling/views/labeling/widgets/image_dialog.py
> +        dst_path.mkdir(parents=True, exist_ok=True)
已去除

2024-12-30 13:09 UTC, chevydream commented on anylabeling/views/labeling/label_widget.py
> +                    self.set_dirty(2)
已移除

2024-12-30 13:09 UTC, chevydream commented on anylabeling/views/labeling/widgets/image_dialog.py
> +                    score = score if score is not None else 0.99
已移除

2024-12-30 13:09 UTC, chevydream commented on anylabeling/views/labeling/widgets/image_dialog.py
> +                    score = shape.get("score", 0.99)
已移除

2024-12-30 13:13 UTC, merged